### ISSUE TITLE
Delete Mediator.Request and stick with Send

### ISSUE THREAD

**Issue by LosGlennos** [alveflo/tsmediator#10]
Is `Mediator.Request` redundant and can it be removed?

I'm thinking that the mediator shouldn't really be aware of the function of what the handlers are doing.

**Comment by alveflo** [comment]
Yep, it's redundant and it can be removed... Stick with `Send`  sounds good to me

**Comment by LosGlennos** [comment]
`Mediator.Request` is still specified in the readme.
