### ISSUE TITLE
Strategy for registering Handlers in non-imported files?

### ISSUE THREAD

**Issue by wovalle** [alveflo/tsmediator#12]
Hey! Nice mediator implementation!

I'm currently implementing tsmediator in a project and found an issue (not the library's fault though).

Let's say I have a `commands` folder with different commands and there I write all my CommandHandlers (in different files). In the index file for the project I make a switch statement and dispatch the commands for the incoming requests.

The thing is that since I never imported the files in `commands/*` typescript doesn't evaluate the `@Handler` decorator so it results in `Handler for command not registered!`.

As a workaround, I'm importing the handlers in my index file and accessing handler.name so I'm forcing it to register the handler.

Any ideas how to register handlers for non-imported files?
Library version: 0.0.4

**Comment by alveflo** [comment]
Hmm unfortunately you have to import the handlers somewhere in your application, otherwise they won't be evaluated. I think that the only strategy that makes sense would be to, as you said already, import the handlers in your index file.

Another approach that I use in another decorator based project (https://github.com/alveflo/ts-unit) is to dynamically importing all typescript files in a given directory;
```
for (const file of GetFilesFromDirectory())
   require(file);
```

That's a bit hacky though but works for a tool or server application.

If you are using a bundler like webpack, maybe it will work if you just include your `commands/*` to be bundled but I'm not sure... Let me know if you come up with a good strategy 😄

**Comment by wovalle** [comment]
I'm currently working in a server application (and apart from the CommandHandlers, I have my own decorators) and I'm facing the same problem. I ended up with something similar to your solution.

I checked how other guys are doing it. TypeORM and Typescript-ioc are doing a similar thing requiring to specify your models/dependencies path so they can scan it.

I think that if you're using this library in your browser and bundling with Webpack (or some other Tree-shakeable bundler) and you don't import the classes, they'll be tree-shaked (if that's even a word).

I'll try to get a better solution in the next coming days, if not, I think something similar to what we have implemented should be baked into the library.

**Comment by alveflo** [comment]
Yep I think that's the way to go.

Yeah sure, let me know if you find anything. I'll leave this issue open for now

**Comment by alveflo** [comment]
Hey @wovalle did you come up with any ideas?

**Comment by wovalle** [comment]
Hey man! Sorry for the delay.

I couldn't come with a better solution for this problem. I was trying to somehow force the [typescript module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html) to evaluate arbitrary files but I couldn't make it work back then, probably will give it another shot soon.

Anyway, for now I only see two possible implementations to solve this issue:
- Require to manually register the handlers in an index file
- Require to write a `tsmediator` property in package.json (or `.tsmediatorrc.json`) and import whatever file is put there (it should accept blobs too).

I'm inclined for a mix of the two. Have the ability to register modules manually (maybe export a `register` function that receives a CommandHandler?) and register many modules at once (export something like `registerPath` that accepts one/many glob patterns and scan the files).

What do you think?

**Comment by alveflo** [comment]
No worries!

Sounds good to me! I guess we can just extend the `Container` to provide that functionality.

From a "library perspective" though I think it makes most sense to focus on the manual registration part. If we can make that good enough then, as a user of this library, one can implement an automatic registration process or whatever in a way that suits the rest of the application.

**Comment by wovalle** [comment]
Sounds good! I'll provide a PR in the coming days then!

**Comment by wovalle** [comment]
Hey! I started the implementation of this but I got stuck. My idea was to store in memory when the users registered a module. I makes sense but at the end tsmediator doesn't do anything with the registration.

At the end, this feature is meant to enforce users to require all the mediators somewhere so Handler decorator is triggered each case. It shouldn't matter what we do with the registration, right?

I could cross what handlers you registered with Container.register vs the handlers that triggered the Handler decorator and throw an error, but at the end the library is already doing this so I don't see the advantage.

In this commit you can see what I meant by "storing the references in memory", see registeredHandlers.
https://github.com/wovalle/tsmediator/commit/9fb40143f07acf66955752d865e4f8826df2e012

What do you think? We should just provide the capability to register the Handler even if we don't do anything with that just to enforce the user to manually import files?

**Comment by alveflo** [comment]
Hey man, sorry for the delay.

I think it looks good. I like the idea of registering handlers manually, we should definately add that functionality. 
Even if we don't do anything with the registration we still need to do it, right. Let's say that you have more than one handler consuming the same message we need to register all of the handlers and the only way one can do that is by doing it manually.

Not sure wheter this answers your question or not haha...

**Comment by wovalle** [comment]
Yes it does! I'll add the tests and submit a pr soon then.

**Comment by alveflo** [comment]
Sweet!
