### ISSUE TITLE
Required properties in command handler

### ISSUE THREAD

**Issue by wovalle** [alveflo/tsmediator#13]
Right now, to implement ICommandHandler or IQueryHandler I must implement a `Log` and `Validate` function in my class, even if I don't want to use either.

I think that the only required property should be `Handle`.

I would understand if the definitive api for the library enforces all the properties to be required.

Pd. I can definitely make a pull request with this change if the idea is accepted :)

**Comment by alveflo** [comment]
Yep I guess we can make `Log` and `Validate` optional so that you're not forced to implement those functions.

Change of the idea is accepted so feel free to submit a pull request :smile:

**Comment by alveflo** [comment]
Fixed by #14 

Feature released to npm with version `0.0.5`
