### ISSUE TITLE
No exported member 'Container'

### ISSUE THREAD

**Issue by jacobbellatorum** [alveflo/tsmediator#20]
Using `import { Container } from 'tsmediator';` results in this error: 

> 'Module "../../../../../Users/username/Documents/Projects/mediator/node_modules/tsmediator/lib"' has no exported member 'Container'. Did you mean 'IContainer'?

**Comment by alveflo** [comment]
Thanks for reporting this. I'll look into it as soon as possible, meanwhile please use the decorator to register handlers.

**Comment by forrestab** [comment]
I am having the same problem, however, I am trying to use it inside of my custom mediator class. Is the fix as simple as adding an export for container in the _index.ts_ file?

**Comment by alveflo** [comment]
@jacobbellatorum so sorry for the delay, I had alot of stuff at work to do during december so totally forgot about this.

@forrestab yup, that's right it's as simple as that.

Anyway, this should be fixed now in v. 0.1.5.
