### ISSUE TITLE
npm install - no src?

### ISSUE THREAD

**Issue by IRCraziestTaxi** [alveflo/tsmediator#3]
I installed tsmediator via `npm install --save tsmediator` and upon installation there is no source code in the npm module, so the module is not found when I try to import the module in my code. Am I missing something?

**Comment by alveflo** [comment]
sounds about right, the source code is ignored by npm since it just needs the lib to run. however that might not be the best way to go and it sounds strange that the module wasn't found... I will look into it and get back to you. thanks for your input!

**Comment by alveflo** [comment]
hey @IRCraziestTaxi , sorry for the delay. this should be fixed now in the latest npm release :) 

closing this one, please reopen or create another issue if you encounter anything else
